;
/* module-key = 'com.atlassian.jira.plugins.jira-editor-plugin:converter-util', location = '/js/converter/util/color-converter.js' */
define("jira/editor/converter/util/color-converter",["exports"],function(a){a.colorToHex=function b(d){if(d.substr(0,1)==="#"){return d}var g=/(.*?)rgb\((\d+), (\d+), (\d+)\)/.exec(d);var h=g[2];var f=g[3];var c=g[4];var e=[h,f,c].map(function(i){return("00"+parseInt(i).toString(16)).slice(-2)});return g[1]+"#"+e.join("")}});;
;
/* module-key = 'com.atlassian.jira.plugins.jira-editor-plugin:converter-util', location = '/js/converter/util/strings.js' */
define("jira/editor/converter/util/strings",["jira/editor/util/strings","exports","jquery","underscore"],function(c,e,f,i){var h="/images/icons/emoticons/";var a="/secure/attachment/";var d="/secure/thumbnail/";e.asBooleanOrString=function b(l){var k=l?l.toLowerCase():"";var j=l;if(k==="true"){j=true}else{if(k==="false"){j=false}}return j};e.startsWith=function(k,j){if(i.isEmpty(k)){return false}if(i.isEmpty(j)){return false}return k.indexOf(j)===0};e.endsWith=function(k,j){if(i.isEmpty(k)){return false}if(i.isEmpty(j)){return false}return k.indexOf(j)+j.length===k.length};e.substringAfter=function(l,j){if(i.isEmpty(l)){return l}if(i.isEmpty(j)){return""}var k=l.indexOf(j);if(k<0){return""}return l.substring(k+j.length)};e.substringBefore=function(l,j){if(i.isEmpty(l)){return l}if(i.isEmpty(j)){return""}var k=l.indexOf(j);if(k<0){return""}return l.substring(0,k)};e.contains=function(l,j){if(i.isEmpty(l)){return false}var k=l.indexOf(j);return k>=0};e.repeat=function(k,j){if(i.isEmpty(k)){return""}return new Array(j+1).join(k)};e.length=function(j){if(i.isEmpty(j)){return 0}return j.length};e.replace=function(o,l,j){if(i.isEmpty(o)){return""}if(i.isEmpty(l)){return""}if(typeof j==="undefined"){j=""}var p=0;var m=o.indexOf(l);while(m>=0){var k=o.substring(0,m);var n=o.substring(m+l.length);o=k+j+n;p=m+j.length;m=o.indexOf(l,p)}return o.substring(m,o.length)};e.hashCode=function g(l){var j;var m=0;if(!l){return""}for(var k=0;k<l.length;k+=1){j=l.charCodeAt(k);m=(m*31)+j;m|=0}return""+m};e.resolveUrl=function(k,l){if(!k){return}var j=f(document.createElement("base")).prop("href",l).appendTo("head");try{return f(document.createElement("a")).prop("href",k).prop("href")}finally{j.remove()}};e.getBaseUrl=function(){return document.location.origin+document.location.pathname};e.getContextUrl=function(){return document.location.origin+AJS.contextPath()};e.getFilenameFromHref=function(l){var j=l.split("/");var k=j[j.length-1];var n=j[j.length-2];var m=n+"_";if(k.indexOf(m)===0){k=k.substring(m.length)}k=k.replace(new RegExp("\\+","g")," ");return decodeURIComponent(k)};e.isAttachmentPath=function(j){return e.contains(j,a)};e.isThumbnailPath=function(j){return e.contains(j,d)};e.isEmotePath=function(j){return e.contains(j,h)};e.getFilenameFromError=function(j){return c.getFilenameFromError(j)}});;
;
/* module-key = 'com.atlassian.jira.plugins.jira-editor-plugin:converter-util', location = '/js/converter/util/uri.js' */
define("jira/editor/converter/util/uri",["exports","atlassian/libs/uri-1.14.1"],function(a,b){a.decodeUri=function(c){return b.decodeQuery(c||"",true)};a.encodeUri=function(c){return b.encodeQuery(c||"",true)}});;
;
/* module-key = 'com.atlassian.jira.plugins.jira-editor-plugin:converter-util', location = '/js/converter/util/rte-strings.js' */
define("jira/editor/converter/util/rte-strings",["exports","underscore"],function(a,b){a.isWhitespace=function(e){if(b.isEmpty(e)){return false}var d={"\t":1,"\n":1,"\u0020":1,"\u0009":1,"\u000A":1,"\u000D":1,"\u000C":1,"\u200B":1};var c=true;b.each(e,function(f){c=c&&(f in d)});return c};a.trim=function(c){if(b.isEmpty(c)){return""}return this.trimLeading(this.trimTrailing(c))};a.trimTrailing=function(d){if(b.isEmpty(d)){return""}var c;for(c=d.length-1;c>=0;c--){if(!this.isWhitespace(d[c])){break}}return d.substring(0,c+1)};a.trimLeading=function(d){if(b.isEmpty(d)){return""}var c;for(c=0;c<d.length;c++){if(!this.isWhitespace(d[c])){break}}return d.substring(c,d.length)};a.parseHtml=function(c){var e=new DOMParser();var d=e.parseFromString(c,"text/html").body;return d}});;